### ISSUE TITLE
Error unexpected token when building with webpack

### ISSUE THREAD

**Issue by sunehs** [ville-j/level-editor-gui#1]
Getting the following error when running yarn run build in the elmaonline-site project.

ERROR in 1.b469f67a.chunk.js from UglifyJs
Unexpected token: name (LevelEditorGUI) [./node_modules/level-editor-gui/src/index.js:4,0][1.b469f67a.chunk.js:1669,6]

**Comment by ville-j** [comment]
Here's something about similar issues: [https://github.com/webpack/webpack/issues/2972#issuecomment-261705632](https://github.com/webpack/webpack/issues/2972#issuecomment-261705632).

**Comment by sunehs** [comment]
Okay so it's not really an issue specifically with this library. In case others with same issue finds this, options are to translate library to non es6, remove the UglifyJs minifier from build process, or use a different one that supports es6, such as the harmony branch of the same.
